language: python
python:
    - 2.6
    - 2.7
env:
    - DJANGO_VERSION=1.1.4
    - DJANGO_VERSION=1.2.7
    - DJANGO_VERSION=1.3.5
    - DJANGO_VERSION=1.4.3
install:
    - pip install -q Django==$DJANGO_VERSION --use-mirrors
    - python setup.py -q install
script:
    - python mathfilters/tests.py
